word1 = input()
word2 = input()
word3 = input()
word4 = input()
word5 = input()
word6 = input()
word7 = input()
word8 = input()
word9 = input()

print(word1, word2, word3, word4, word5, word6, word7, word8, word9)